name: Build Site
on:
  pull_request:
    branches: [source]
  push:
    branches: [source]

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          
    - name: Install dependencies
      run: |
        npm install
        npm install -g yarn
        npm install -g gatsby-cli
        yarn
        sudo apt install python3
 
    - name: Build UTBot Site
      run: |
        npm run build
        pwd && ls
 
    - name: Deploy UTBot Site
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        pwd && ls
        cp -r public ../
        git fetch
        git checkout main
        rm -r *
        cp -atr ../public .
        git add .
        git commit -am "Update Site content"
        git push
        pwd && ls
