name: Build and Deploy Site
on:
  push:
    branches: [source]

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          
    - name: Install dependencies
      run: |
        sudo npm install
        sudo npm install -g yarn
        sudo npm install -g gatsby-cli
        sudo yarn
        sudo apt install python3
 
    - name: Build UTBot Site
      run:
        sudo npm run build
 
    - name: Deploy UTBot Site
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        sudo cp -r public /usr
        git fetch
        git clean -f -d
        git checkout main
        rm -rf *
        sudo cp -r /usr/public/* .
        touch CNAME
        echo "www.utbot.org" >> CNAME
        git add .
        git commit -am ${{ github.event.head_commit.message }}
        git push
