name: Build Site
on:
  pull_request:
    branches: [source]
  push:
    branches: [source]

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest    
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-associations: '["CONTRIBUTOR"]'
          
    - name: Install dependencies
      run: |
        npm install
        npm install -g yarn
        npm install -g gatsby-cli
        yarn
        sudo apt install python3
 
    - name: Build UTBot Site
      run: npm run build
 
    - name: Deploy UTBot Site
      run: |
        pwd
