name: Build and Deploy Site
on:
  push:
    branches: [source]

jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: '18'

    - name: Install dependencies
      run: |
        set -o xtrace
        npm install -g yarn 
        npm install -g gatsby-cli
        
    - name: Install packages
      run: |
        set -o xtrace
        npm install
        yarn
        
    - name: Build UTBot Site
      run:
        npm run build

    - name: Deploy UTBot Site
      run: |
        set -o xtrace
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        sudo cp -r public /usr
        git fetch
        git stash
        git checkout main
        sudo rm -rf *
        sudo cp -r /usr/public/* .
        touch CNAME
        echo "www.utbot.org" >> CNAME
        git add .
        git commit -am "${{ github.event.head_commit.message }}"
        git push
