name: Build Site
on:
  workflow_dispatch:
  pull_request:
    branches: [source]

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: '18'

    - name: Install dependencies
      run: |
        set -o xtrace
        npm install -g yarn 
        npm install -g gatsby-cli
        
    - name: Install packages
      run: |
        set -o xtrace
        npm install
        yarn

    - name: Build UTBot Site
      run:
        npm run build
