name: Build Site
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '14'
          
    - name: Install dependencies
      run:
        npm install -g yarn
        npm install -g gatsby-cli
        yarn install
          
    - name: Build Site
      run: npm run develop
